apiVersion: v1
kind: Service
metadata:
   name: daemon-lb
   namespace: dev
spec:
  type: LoadBalancer
  selector:
     app: daemon
  ports:
    - protocol: TCP
      port: 9100
      targetPort: 9100
