apiVersion: v1
kind: PersistentVolume
metadata:
  name: nginx-pv
  namespace: dev
spec:
  capacity:
   storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentvolumereclaimPolicy: Retain
  awselasticblockstorage:
     volumeId: vol-07e18e7c0424ed4d6
