# mysql-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: db      # ✅ matches what your PHP app uses in mysqli_connect()
spec:
  selector:
    app: mysql
  ports:
  - protocol: TCP
    port: 3306
    targetPort: 3306
